'use client';

import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Archive, CheckCircle2, FileVideo2, Loader2, Plus, RefreshCcw, Save, Sparkles, Upload } from 'lucide-react';
import apiClient from '@/lib/api';
import { useAdminAuthStore } from '@/stores/admin-auth.store';

type Line = 'viral_presets' | 'ai_presets' | 'mv_templates';
interface FormRow { code: string; nameEn: string; nameZh: string; executorKey: string; inputSchema: Record<string, unknown>; uiSchema: Record<string, unknown>; outputSchema: Record<string, unknown>; enabled: boolean }
interface ModelRow { code: string; label: string; provider: string; exactModel: string; capability: string; defaultParams: Record<string, unknown>; allowedParams: string[]; enabled: boolean }
interface VersionRow { id: string; versionNumber: number; status: string; nameEn: string; coverUrl: string; previewVideoUrl: string; source?: string | null; modelCode?: string | null; priceCredits: number; inputSchema: Record<string, unknown>; uiSchema: Record<string, unknown>; executionConfig: Record<string, unknown> }
interface ProductRow { id: string; slug: string; line: Line; formCode: string; status: string; featured: boolean; sortOrder: number; currentVersionId?: string | null; versions: VersionRow[] }
interface TaskRow { id: string; userId: string; status: string; stage: string; productLine: string; quoteCredits: number; providerTaskId?: string | null; errorMessage?: string | null; createdAt: string }

const emptyProduct = { slug: '', line: 'ai_presets' as Line, formCode: 'single_image_video', nameEn: '', nameZh: '', descriptionEn: '', descriptionZh: '', coverUrl: '', previewVideoUrl: '', source: '', modelCode: '', priceCredits: 30, sortOrder: 0, featured: false, inputSchema: '{\n  "type": "object",\n  "required": ["image"],\n  "properties": {\n    "image": { "title": "Image", "format": "image" },\n    "prompt": { "title": "Prompt", "format": "textarea" }\n  }\n}', uiSchema: '{}', executionConfig: '{}' };

export default function InspirationAdminPage() {
  const [tab, setTab] = useState<'products'|'forms'|'models'|'tasks'>('products');
  return <div className="space-y-6 p-6"><header><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-600">New product domain</p><h1 className="mt-1 text-2xl font-bold text-slate-900">Inspiration</h1><p className="mt-1 text-sm text-slate-500">配置产品形态、版本化模板、模型绑定与运行任务。现有 Create MV 不受这里的设置影响。</p></header>
    <nav className="flex gap-1 rounded-xl border border-slate-200 bg-white p-1">{([['products','产品与版本'],['forms','产品形态'],['models','模型'],['tasks','任务']] as const).map(([key,label]) => <button key={key} onClick={() => setTab(key)} className={`rounded-lg px-4 py-2 text-sm font-medium ${tab === key ? 'bg-violet-600 text-white' : 'text-slate-600 hover:bg-slate-50'}`}>{label}</button>)}</nav>
    {tab === 'products' ? <ProductsTab /> : tab === 'forms' ? <FormsTab /> : tab === 'models' ? <ModelsTab /> : <TasksTab />}
  </div>;
}

function ProductsTab() {
  const qc = useQueryClient(); const canEdit = useAdminAuthStore((s) => s.hasPermission('inspiration.content.edit')); const canPublish = useAdminAuthStore((s) => s.hasPermission('inspiration.content.publish'));
  const products = useQuery<ProductRow[]>({ queryKey: ['inspiration','products'], queryFn: () => apiClient.get('/admin/inspiration/products') as Promise<ProductRow[]> });
  const forms = useQuery<FormRow[]>({ queryKey: ['inspiration','forms'], queryFn: () => apiClient.get('/admin/inspiration/forms') as Promise<FormRow[]> });
  const models = useQuery<ModelRow[]>({ queryKey: ['inspiration','models'], queryFn: () => apiClient.get('/admin/inspiration/models') as Promise<ModelRow[]> });
  const [draft, setDraft] = useState(emptyProduct); const [targetId, setTargetId] = useState<string>(); const [error, setError] = useState<string>();
  const save = useMutation({ mutationFn: async () => {
    const body = { ...draft, inputSchema: parseJson(draft.inputSchema, 'Input Schema'), uiSchema: parseJson(draft.uiSchema, 'UI Schema'), executionConfig: parseJson(draft.executionConfig, 'Execution Config'), modelCode: draft.modelCode || null };
    return targetId ? apiClient.post(`/admin/inspiration/products/${targetId}/versions`, body) : apiClient.post('/admin/inspiration/products', body);
  }, onSuccess: () => { setDraft(emptyProduct); setTargetId(undefined); setError(undefined); void qc.invalidateQueries({ queryKey: ['inspiration','products'] }); }, onError: (value) => setError(message(value)) });
  const action = useMutation({ mutationFn: ({ kind, productId, versionId }: { kind: 'publish'|'archive'; productId: string; versionId?: string }) => kind === 'publish' ? apiClient.post(`/admin/inspiration/products/${productId}/versions/${versionId}/publish`) : apiClient.post(`/admin/inspiration/products/${productId}/archive`), onSuccess: () => void qc.invalidateQueries({ queryKey: ['inspiration','products'] }) });
  const editAsVersion = (product: ProductRow, version: VersionRow) => { setTargetId(product.id); setDraft({ slug: product.slug, line: product.line, formCode: product.formCode, nameEn: version.nameEn, nameZh: '', descriptionEn: '', descriptionZh: '', coverUrl: version.coverUrl, previewVideoUrl: version.previewVideoUrl, source: version.source || '', modelCode: version.modelCode || '', priceCredits: version.priceCredits, sortOrder: product.sortOrder, featured: product.featured, inputSchema: pretty(version.inputSchema), uiSchema: pretty(version.uiSchema), executionConfig: pretty(version.executionConfig) }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <div className="space-y-6"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold text-slate-900">{targetId ? '创建新版本' : '新建模板'}</h2><p className="text-xs text-slate-500">已发布版本不可直接修改；编辑会创建新草稿版本。</p></div>{targetId ? <button onClick={() => { setTargetId(undefined); setDraft(emptyProduct); }} className="text-sm text-slate-500">取消</button> : null}</div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Input label="Slug" value={draft.slug} disabled={!!targetId} onChange={(slug) => setDraft({ ...draft, slug })}/><Select label="产品线" value={draft.line} options={[['viral_presets','Viral Presets'],['ai_presets','AI Presets'],['mv_templates','MV Templates']]} onChange={(line) => setDraft({ ...draft, line: line as Line })}/><Select label="产品形态" value={draft.formCode} options={(forms.data ?? []).map((row): [string, string] => [row.code, `${row.nameEn} · ${row.code}`])} onChange={(formCode) => setDraft({ ...draft, formCode })}/><Select label="逻辑模型" value={draft.modelCode} options={[['','请选择'],...(models.data ?? []).map((row): [string, string] => [row.code, `${row.label} · ${row.provider}`])]} onChange={(modelCode) => setDraft({ ...draft, modelCode })}/><Input label="英文名称" value={draft.nameEn} onChange={(nameEn) => setDraft({ ...draft, nameEn })}/><Input label="中文名称" value={draft.nameZh} onChange={(nameZh) => setDraft({ ...draft, nameZh })}/><NumberInput label="Credits" value={draft.priceCredits} onChange={(priceCredits) => setDraft({ ...draft, priceCredits })}/><NumberInput label="排序" value={draft.sortOrder} onChange={(sortOrder) => setDraft({ ...draft, sortOrder })}/></div>
    <div className="mt-4 grid gap-4 md:grid-cols-2"><Textarea label="英文描述" value={draft.descriptionEn} onChange={(descriptionEn) => setDraft({ ...draft, descriptionEn })}/><Textarea label="中文描述" value={draft.descriptionZh} onChange={(descriptionZh) => setDraft({ ...draft, descriptionZh })}/></div>
    <div className="mt-4 grid gap-4 md:grid-cols-3"><MediaUpload label="封面" kind="cover" value={draft.coverUrl} onChange={(coverUrl) => setDraft({ ...draft, coverUrl })}/><MediaUpload label="预览视频" kind="preview" value={draft.previewVideoUrl} onChange={(previewVideoUrl) => setDraft({ ...draft, previewVideoUrl })}/><Input label="来源（可选）" value={draft.source} onChange={(source) => setDraft({ ...draft, source })}/></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><CodeField label="Input Schema" value={draft.inputSchema} onChange={(inputSchema) => setDraft({ ...draft, inputSchema })}/><CodeField label="UI Schema" value={draft.uiSchema} onChange={(uiSchema) => setDraft({ ...draft, uiSchema })}/><CodeField label="Execution Config" value={draft.executionConfig} onChange={(executionConfig) => setDraft({ ...draft, executionConfig })}/></div>
    <label className="mt-4 flex items-center gap-2 text-sm text-slate-600"><input type="checkbox" checked={draft.featured} onChange={(e) => setDraft({ ...draft, featured: e.target.checked })}/>首页推荐</label>
    {error ? <p className="mt-3 text-sm text-red-600">{error}</p> : null}<button disabled={!canEdit || save.isPending} onClick={() => save.mutate()} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-sm font-medium text-white disabled:opacity-45">{save.isPending ? <Loader2 className="h-4 w-4 animate-spin"/> : <Save className="h-4 w-4"/>}{targetId ? '保存新版本' : '创建模板'}</button>
  </section>
  <section className="overflow-hidden rounded-xl border border-slate-200 bg-white">{products.isLoading ? <Loading/> : <div className="divide-y divide-slate-100">{products.data?.map((product) => { const latest = product.versions[0]; return <article key={product.id} className="p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-4">{latest?.coverUrl ? <img src={latest.coverUrl} alt="" className="h-20 w-20 rounded-lg object-cover"/> : <div className="h-20 w-20 rounded-lg bg-slate-100"/>}<div><div className="flex items-center gap-2"><h3 className="font-semibold text-slate-900">{latest?.nameEn || product.slug}</h3><Badge value={product.status}/></div><p className="mt-1 text-xs text-slate-500">{product.line} · {product.formCode} · {product.slug}</p><p className="mt-2 text-xs text-slate-500">{product.versions.length} 个版本 · 当前 v{product.versions.find((v) => v.id === product.currentVersionId)?.versionNumber ?? '—'}</p></div></div><div className="flex gap-2">{latest ? <button disabled={!canEdit} onClick={() => editAsVersion(product, latest)} className="rounded-lg border border-slate-200 px-3 py-2 text-xs">创建新版本</button> : null}{latest?.status === 'draft' ? <button disabled={!canPublish || action.isPending} onClick={() => action.mutate({ kind: 'publish', productId: product.id, versionId: latest.id })} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs text-white"><CheckCircle2 className="h-3.5 w-3.5"/>发布 v{latest.versionNumber}</button> : null}<button disabled={!canPublish || action.isPending} onClick={() => action.mutate({ kind: 'archive', productId: product.id })} className="rounded-lg border border-slate-200 p-2 text-slate-500"><Archive className="h-4 w-4"/></button></div></div></article>; })}{!products.data?.length ? <Empty text="尚未创建 Inspiration 模板"/> : null}</div>}</section></div>;
}

function FormsTab() {
  const qc = useQueryClient(); const query = useQuery<FormRow[]>({ queryKey: ['inspiration','forms'], queryFn: () => apiClient.get('/admin/inspiration/forms') as Promise<FormRow[]> }); const [selected, setSelected] = useState<FormRow>();
  const save = useMutation({ mutationFn: (row: FormRow) => apiClient.put(`/admin/inspiration/forms/${row.code}`, row), onSuccess: () => { setSelected(undefined); void qc.invalidateQueries({ queryKey: ['inspiration','forms'] }); } });
  if (query.isLoading) return <Loading/>;
  return <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><section className="rounded-xl border border-slate-200 bg-white p-3">{query.data?.map((row) => <button key={row.code} onClick={() => setSelected({ ...row })} className="block w-full rounded-lg px-3 py-3 text-left hover:bg-slate-50"><span className="block text-sm font-medium text-slate-900">{row.nameEn}</span><span className="text-xs text-slate-500">{row.code} · {row.executorKey}</span></button>)}</section><section className="rounded-xl border border-slate-200 bg-white p-5">{selected ? <><h2 className="font-semibold">编辑产品形态</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><Input label="英文名称" value={selected.nameEn} onChange={(nameEn) => setSelected({ ...selected, nameEn })}/><Input label="执行器" value={selected.executorKey} onChange={(executorKey) => setSelected({ ...selected, executorKey })}/></div><div className="mt-4 grid gap-4 xl:grid-cols-3"><ObjectCodeField label="Input Schema" value={selected.inputSchema} onChange={(inputSchema) => setSelected({ ...selected, inputSchema })}/><ObjectCodeField label="UI Schema" value={selected.uiSchema} onChange={(uiSchema) => setSelected({ ...selected, uiSchema })}/><ObjectCodeField label="Output Schema" value={selected.outputSchema} onChange={(outputSchema) => setSelected({ ...selected, outputSchema })}/></div><button onClick={() => save.mutate(selected)} className="mt-5 rounded-lg bg-violet-600 px-4 py-2 text-sm text-white">保存</button></> : <Empty text="选择一个产品形态进行配置"/>}</section></div>;
}

function ModelsTab() {
  const qc = useQueryClient(); const query = useQuery<ModelRow[]>({ queryKey: ['inspiration','models'], queryFn: () => apiClient.get('/admin/inspiration/models') as Promise<ModelRow[]> }); const [row, setRow] = useState<ModelRow>({ code: '', label: '', provider: 'mountsea', exactModel: '', capability: 'videoSingleRef', defaultParams: {}, allowedParams: [], enabled: true });
  const save = useMutation({ mutationFn: () => apiClient.put(`/admin/inspiration/models/${row.code}`, row), onSuccess: () => { setRow({ code: '', label: '', provider: 'mountsea', exactModel: '', capability: 'videoSingleRef', defaultParams: {}, allowedParams: [], enabled: true }); void qc.invalidateQueries({ queryKey: ['inspiration','models'] }); } });
  return <div className="grid gap-5 xl:grid-cols-[1fr_420px]"><section className="overflow-hidden rounded-xl border border-slate-200 bg-white">{query.isLoading ? <Loading/> : <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">逻辑模型</th><th className="p-3">Provider / 精确模型</th><th className="p-3">能力</th><th className="p-3">状态</th></tr></thead><tbody className="divide-y">{query.data?.map((model) => <tr key={model.code} onClick={() => setRow({ ...model })} className="cursor-pointer hover:bg-slate-50"><td className="p-3"><b>{model.label}</b><div className="text-xs text-slate-500">{model.code}</div></td><td className="p-3">{model.provider}<div className="text-xs text-slate-500">{model.exactModel}</div></td><td className="p-3">{model.capability}</td><td className="p-3">{model.enabled ? '启用' : '停用'}</td></tr>)}</tbody></table>}</section><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">{row.code ? '编辑模型' : '新增逻辑模型'}</h2><div className="mt-4 space-y-4"><Input label="模型编码" value={row.code} onChange={(code) => setRow({ ...row, code })}/><Input label="显示名称" value={row.label} onChange={(label) => setRow({ ...row, label })}/><Select label="Provider" value={row.provider} options={['mountsea','apisale','smartfashion','aitokens'].map((v) => [v,v])} onChange={(provider) => setRow({ ...row, provider })}/><Input label="精确模型 ID" value={row.exactModel} onChange={(exactModel) => setRow({ ...row, exactModel })}/><Select label="Capability" value={row.capability} options={['videoSingleRef','videoMultiRef','videoLipsync','imageNanoBanana'].map((v) => [v,v])} onChange={(capability) => setRow({ ...row, capability })}/><ObjectCodeField label="默认参数" value={row.defaultParams} onChange={(defaultParams) => setRow({ ...row, defaultParams })}/><Input label="允许用户覆盖的参数（逗号分隔）" value={row.allowedParams.join(', ')} onChange={(value) => setRow({ ...row, allowedParams: value.split(',').map((item) => item.trim()).filter(Boolean) })}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={row.enabled} onChange={(e) => setRow({ ...row, enabled: e.target.checked })}/>启用</label></div><button disabled={save.isPending || !row.code} onClick={() => save.mutate()} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-sm text-white disabled:opacity-45"><Save className="h-4 w-4"/>保存模型</button></section></div>;
}

function TasksTab() { const [status,setStatus] = useState(''); const query = useQuery<TaskRow[]>({ queryKey: ['inspiration','tasks',status], queryFn: () => apiClient.get('/admin/inspiration/tasks', { params: { status } }) as Promise<TaskRow[]>, refetchInterval: 10000 }); return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b p-4"><h2 className="font-semibold">生成任务</h2><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">全部状态</option>{['reserving','queued','processing','submission_unknown','succeeded','failed','cancelled'].map((v) => <option key={v}>{v}</option>)}</select></div>{query.isLoading ? <Loading/> : <table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="p-3">任务</th><th className="p-3">产品线</th><th className="p-3">状态 / 阶段</th><th className="p-3">Credits</th><th className="p-3">创建时间</th></tr></thead><tbody className="divide-y">{query.data?.map((task) => <tr key={task.id}><td className="p-3 font-mono text-xs">{task.id}</td><td className="p-3">{task.productLine}</td><td className="p-3"><Badge value={task.status}/><div className="mt-1 text-xs text-slate-500">{task.stage}</div></td><td className="p-3">{task.quoteCredits}</td><td className="p-3 text-xs text-slate-500">{new Date(task.createdAt).toLocaleString()}</td></tr>)}</tbody></table>}</section>; }

function MediaUpload({ label, kind, value, onChange }: { label: string; kind: 'cover'|'preview'; value: string; onChange: (value: string) => void }) { const [busy,setBusy] = useState(false); const upload = async (file?: File) => { if (!file) return; setBusy(true); try { const form = new FormData(); form.append('file', file); form.append('kind', kind); const result = await apiClient.post('/admin/inspiration/media/upload', form, { headers: { 'Content-Type': 'multipart/form-data' } }) as { url: string }; onChange(result.url); } finally { setBusy(false); } }; return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><span className="flex h-24 cursor-pointer items-center justify-center overflow-hidden rounded-lg border border-dashed border-slate-300 bg-slate-50">{value ? kind === 'cover' ? <img src={value} alt="" className="h-full w-full object-cover"/> : <span className="flex items-center gap-2 text-xs text-slate-600"><FileVideo2 className="h-4 w-4"/>已上传预览视频</span> : busy ? <Loader2 className="h-5 w-5 animate-spin"/> : <span className="flex items-center gap-2 text-xs text-slate-500"><Upload className="h-4 w-4"/>上传{label}</span>}</span><input type="file" accept={kind === 'cover' ? 'image/*' : 'video/*'} className="hidden" onChange={(e) => void upload(e.target.files?.[0])}/></label>; }
function Input({ label,value,onChange,disabled }: { label:string; value:string; onChange:(v:string)=>void; disabled?:boolean }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><input disabled={disabled} value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-violet-400 disabled:bg-slate-100"/></label>; }
function NumberInput({ label,value,onChange }: { label:string; value:number; onChange:(v:number)=>void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><input type="number" value={value} onChange={(e)=>onChange(Number(e.target.value))} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-violet-400"/></label>; }
function Select({ label,value,options,onChange }: { label:string; value:string; options:Array<[string,string]>; onChange:(v:string)=>void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><select value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>; }
function Textarea({ label,value,onChange }: { label:string; value:string; onChange:(v:string)=>void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><textarea rows={3} value={value} onChange={(e)=>onChange(e.target.value)} className="w-full rounded-lg border border-slate-200 px-3 py-2 text-sm outline-none focus:border-violet-400"/></label>; }
function CodeField({ label,value,onChange }: { label:string; value:string; onChange:(v:string)=>void }) { return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><textarea rows={10} value={value} onChange={(e)=>onChange(e.target.value)} spellCheck={false} className="w-full rounded-lg border border-slate-200 bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100 outline-none focus:border-violet-400"/></label>; }
function ObjectCodeField({ label, value, onChange }: { label: string; value: Record<string, unknown>; onChange: (value: Record<string, unknown>) => void }) { const serialized = pretty(value); const [draft, setDraft] = useState(serialized); const [invalid, setInvalid] = useState(false); useEffect(() => setDraft(serialized), [serialized]); return <label className="block"><span className="mb-1 block text-xs font-medium text-slate-600">{label}</span><textarea rows={10} value={draft} onChange={(event) => { const next = event.target.value; setDraft(next); try { const parsed = JSON.parse(next); if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error(); setInvalid(false); onChange(parsed as Record<string, unknown>); } catch { setInvalid(true); } }} spellCheck={false} className={`w-full rounded-lg border bg-slate-950 px-3 py-2 font-mono text-xs text-slate-100 outline-none ${invalid ? 'border-red-500' : 'border-slate-200 focus:border-violet-400'}`}/>{invalid ? <span className="mt-1 block text-xs text-red-600">JSON 格式无效，当前内容不会保存</span> : null}</label>; }
function Badge({ value }: { value:string }) { const cls = value === 'published' || value === 'succeeded' ? 'bg-emerald-50 text-emerald-700' : value === 'failed' || value === 'archived' ? 'bg-red-50 text-red-700' : 'bg-amber-50 text-amber-700'; return <span className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${cls}`}>{value}</span>; }
function Loading(){ return <div className="flex min-h-52 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-slate-400"/></div>; }
function Empty({ text }: { text:string }) { return <div className="flex min-h-52 items-center justify-center text-sm text-slate-400"><Sparkles className="mr-2 h-4 w-4"/>{text}</div>; }
function parseJson(value:string,label:string){ try { return JSON.parse(value) as Record<string,unknown>; } catch { throw new Error(`${label} 不是有效 JSON`); } }
function pretty(value:unknown){ return JSON.stringify(value ?? {}, null, 2); }
function message(error:unknown){ return typeof error === 'object' && error && 'message' in error ? String((error as {message?:unknown}).message) : '保存失败'; }
