'use client';

import { Suspense, useMemo, useState } from 'react';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { Activity, AlertTriangle, Coins, Film, RefreshCw, Route, WalletCards } from 'lucide-react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import apiClient from '@/lib/api';
import { QueryState } from '@/components/query-state';
import { computeRange, RANGE_LABEL, RangePreset, usdAmount } from '../_lib/format';

type Summary = { projects: number; successfulProjects: number; failedProjects: number; chargedCredits: number; generatedSeconds: number; attempts: number; successfulAttempts: number; failedAttempts: number; costReportedAttempts: number; totalUsd: number };
type Breakdown = { provider?: string; model?: string; calls: number; successes: number; failures: number; costReportedCalls: number; usd: number };
type ProjectRow = { id: string; title: string; status: string; model: string; durationSec: number; chargedCredits: number; errorMessage?: string | null; createdAt: string; calls: number; successes: number; failures: number; costReportedCalls: number; usd: number };
type CostData = { range: { from: string; to: string }; summary: Summary; byProvider: Breakdown[]; byModel: Breakdown[]; timeline: Array<{ date: string; calls: number; successes: number; failures: number; usd: number }>; projects: { page: number; pageSize: number; total: number; items: ProjectRow[] } };
const PRESETS: RangePreset[] = ['today', '7d', '30d', '90d', '12m'];

function CostPageContent() {
  const [preset, setPreset] = useState<RangePreset>('30d');
  const [page, setPage] = useState(1);
  const range = useMemo(() => computeRange(preset), [preset]);
  const params = new URLSearchParams({ from: new Date(range.fromMs).toISOString(), to: new Date(range.toMs).toISOString(), page: String(page), pageSize: '20' });
  const query = useQuery<CostData>({ queryKey: ['aimv-cost', preset, page], queryFn: () => apiClient.get(`/admin/aimv-generator/cost/overview?${params}`) as any });
  const data = query.data;
  const summary = data?.summary;
  const coverage = summary?.attempts ? summary.costReportedAttempts / summary.attempts : 0;
  const successRate = summary?.attempts ? summary.successfulAttempts / summary.attempts : 0;
  const pages = Math.max(1, Math.ceil((data?.projects.total ?? 0) / (data?.projects.pageSize ?? 20)));

  return <div className="admin-page"><div className="mx-auto w-full max-w-[1680px] space-y-5 p-6">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-950">AI MV Generator 成本统计</h1><p className="mt-1 text-sm text-slate-500">仅统计新产品 /create-mv 的项目、渠道尝试、积分结算与上游回传成本。</p></div><div className="flex items-center gap-2"><div className="flex rounded-lg border border-slate-200 bg-white p-1">{PRESETS.map((item) => <button key={item} onClick={() => { setPreset(item); setPage(1); }} className={`rounded-md px-3 py-1.5 text-xs font-medium ${preset === item ? 'bg-violet-600 text-white' : 'text-slate-500 hover:bg-slate-50'}`}>{RANGE_LABEL[item]}</button>)}</div><button onClick={() => query.refetch()} className="rounded-lg border border-slate-200 bg-white p-2 text-slate-500 hover:text-violet-600" aria-label="刷新"><RefreshCw className={`h-4 w-4 ${query.isFetching ? 'animate-spin' : ''}`} /></button></div></header>

    <QueryState isLoading={query.isLoading} isError={query.isError} error={query.error} isEmpty={!data} height="h-64">{data && summary && <>
      <section className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-5"><Kpi icon={WalletCards} label="上游已回传成本" value={usdAmount(summary.totalUsd)} sub={`成本覆盖 ${(coverage * 100).toFixed(1)}%`} /><Kpi icon={Film} label="AI MV 项目" value={summary.projects.toLocaleString()} sub={`成功 ${summary.successfulProjects} · 失败 ${summary.failedProjects}`} /><Kpi icon={Route} label="渠道尝试" value={summary.attempts.toLocaleString()} sub={`成功率 ${(successRate * 100).toFixed(1)}%`} /><Kpi icon={Coins} label="成功后扣减积分" value={summary.chargedCredits.toLocaleString()} sub="不包含预扣" /><Kpi icon={Activity} label="成功成片时长" value={`${summary.generatedSeconds.toLocaleString()}s`} sub={`${summary.costReportedAttempts}/${summary.attempts} 次有成本回传`} /></section>
      {summary.costReportedAttempts < summary.attempts && <div className="flex gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" /><span>有 {summary.attempts - summary.costReportedAttempts} 次渠道调用没有回传上游成本；总成本只汇总已回传值，不使用旧业务价格表估算。</span></div>}
      <section className="grid grid-cols-1 gap-4 xl:grid-cols-3"><div className="rounded-xl border border-slate-200 bg-white p-5 xl:col-span-2"><h2 className="font-semibold text-slate-900">每日上游成本</h2><p className="mb-4 text-xs text-slate-400">USD · AI MV 渠道尝试</p><div className="h-72"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.timeline}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => usdAmount(Number(value))} /><Line type="monotone" dataKey="usd" stroke="#7c3aed" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></div></div><BreakdownTable title="渠道分布" rows={data.byProvider} nameKey="provider" /></section>
      <BreakdownTable title="模型成本与成功率" rows={data.byModel} nameKey="model" />
      <ProjectTable data={data} page={page} pages={pages} setPage={setPage} />
      <p className="text-xs leading-5 text-slate-400">口径：页面只读取 AI MV Generator 独立表。上游成本来自渠道尝试记录的 upstream_cost_usd；未回传成本的调用只计次数，不按旧 MV、音乐或其他业务价格表补估。用户积分为任务成功后实际结算值。</p>
    </>}</QueryState>
  </div></div>;
}

function Kpi({ icon: Icon, label, value, sub }: { icon: typeof Film; label: string; value: string; sub: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-xs text-slate-400"><Icon className="h-4 w-4" />{label}</div><div className="mt-2 text-2xl font-bold text-slate-950">{value}</div><div className="mt-1 text-xs text-slate-400">{sub}</div></div>; }

function BreakdownTable({ title, rows, nameKey }: { title: string; rows: Breakdown[]; nameKey: 'provider' | 'model' }) { return <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4 font-semibold text-slate-900">{title}</div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3 text-left">{nameKey === 'provider' ? '渠道' : '模型'}</th><th className="px-3 py-3 text-right">调用</th><th className="px-3 py-3 text-right">成功率</th><th className="px-5 py-3 text-right">成本</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row) => <tr key={String(row[nameKey])}><td className="max-w-md truncate px-5 py-3 font-medium text-slate-700" title={row[nameKey]}>{row[nameKey]}</td><td className="px-3 py-3 text-right text-slate-500">{row.calls}</td><td className="px-3 py-3 text-right text-slate-500">{row.calls ? `${((row.successes / row.calls) * 100).toFixed(1)}%` : '—'}</td><td className="px-5 py-3 text-right font-semibold text-slate-900">{usdAmount(row.usd)}<div className="text-[10px] font-normal text-slate-400">{row.costReportedCalls}/{row.calls} 已回传</div></td></tr>)}</tbody></table></div>{!rows.length && <div className="py-10 text-center text-sm text-slate-400">暂无数据</div>}</div>; }

function ProjectTable({ data, page, pages, setPage }: { data: CostData; page: number; pages: number; setPage: (value: number | ((old: number) => number)) => void }) { return <section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 px-5 py-4"><h2 className="font-semibold text-slate-900">AI MV 项目成本明细</h2><p className="text-xs text-slate-400">点击项目可查看分镜、队列、渠道尝试和完整错误原因</p></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">项目</th><th className="px-4 py-3">状态</th><th className="px-4 py-3">模型 / 时长</th><th className="px-4 py-3">渠道尝试</th><th className="px-4 py-3">已回传成本</th><th className="px-4 py-3">扣减积分</th><th className="px-4 py-3">错误</th></tr></thead><tbody className="divide-y divide-slate-100">{data.projects.items.map((row) => <tr key={row.id} className="hover:bg-slate-50"><td className="px-5 py-3"><Link href={`/admin/ai-music-video/projects/${row.id}`} className="font-medium text-violet-700 hover:underline">{row.title || row.id}</Link><div className="text-[11px] text-slate-400">{row.id}</div></td><td className="px-4 py-3"><Status value={row.status} /></td><td className="px-4 py-3 text-slate-600">{row.model}<div className="text-xs text-slate-400">{row.durationSec}s</div></td><td className="px-4 py-3 text-slate-600">{row.calls}<div className="text-xs text-slate-400">成功 {row.successes} · 失败 {row.failures}</div></td><td className="px-4 py-3 font-medium text-slate-900">{usdAmount(row.usd)}<div className="text-xs font-normal text-slate-400">覆盖 {row.costReportedCalls}/{row.calls}</div></td><td className="px-4 py-3 text-slate-600">{row.chargedCredits}</td><td className="max-w-xs px-4 py-3 text-xs text-rose-600"><span className="line-clamp-2" title={row.errorMessage ?? ''}>{row.errorMessage || '—'}</span></td></tr>)}</tbody></table></div>{!data.projects.items.length && <div className="py-12 text-center text-sm text-slate-400">当前时间范围内暂无 AI MV 项目</div>}<div className="flex items-center justify-between border-t border-slate-100 px-5 py-3 text-xs text-slate-500"><span>共 {data.projects.total} 个项目</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">上一页</button><span className="px-2 py-1.5">{page}/{pages}</span><button disabled={page >= pages} onClick={() => setPage((v) => v + 1)} className="rounded border px-3 py-1.5 disabled:opacity-40">下一页</button></div></div></section>; }
function Status({ value }: { value: string }) { const ok = value === 'succeeded'; const bad = ['failed', 'cancelled'].includes(value); return <span className={`rounded-full px-2 py-1 text-xs font-medium ${ok ? 'bg-emerald-50 text-emerald-700' : bad ? 'bg-rose-50 text-rose-700' : 'bg-blue-50 text-blue-700'}`}>{value}</span>; }
export default function CostPage() { return <Suspense><CostPageContent /></Suspense>; }
